# Generated by Django 5.0.2 on 2024-03-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='can_take_calls',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='coffee_price',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_sockets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_toilet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='map_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='seats',
            field=models.CharField(max_length=250),
        ),
    ]
